# Augmentation Configuration File for YOLOv5 Training

# Image Size
img_size: 640  # Training image size (pixels)

# Random Crop
random_crop:
  enable: True  # Enable random cropping
  min_scale: 0.5  # Minimum crop scale
  max_scale: 0.9  # Maximum crop scale
  min_aspect_ratio: 0.5  # Minimum aspect ratio of the cropped image
  max_aspect_ratio: 2.0  # Maximum aspect ratio of the cropped image

# Flip
flip:
  enable: True  # Enable flipping
  prob: 0.5  # Probability of flipping an image horizontally

# HSV Color Jitter
hsv:
  enable: True  # Enable HSV color jitter
  h_gain: 0.05  # Hue gain
  s_gain: 0.1  # Saturation gain
  v_gain: 0.1  # Value gain

# Blur
blur:
  enable: True  # Enable blurring#train: set your own data path for training 
#val: set your own data path for validation/testing

train : E:\s1\Job\Final\obj
val: E:\s1\Job\Final\test

nc: 2   # number if class , here just two , cat and dog 
names: ['cat', 'dog'] # class name



# data augmentation 
img_size: 640
random_crop:
  enable: True
  min_scale: 0.5
  max_scale: 0.9
  min_aspect_ratio: 0.5
  max_aspect_ratio: 2.0
flip:
  enable: True
  prob: 0.5
hsv:
  enable: True
  h_gain: 0.05
  s_gain: 0.1
  v_gain: 0.1
blur:
  enable: True
  prob: 0.2
  radius: 1.0
noise:
  enable: True
  prob: 0.1
  amount: 0.01
perspective:
  enable: True
  prob: 0.05
  distortion_scale: 0.1
random_erasing:
  enable: True
  prob: 0.5
  min_area: 0.1
  max_area: 0.3
  min_aspect_ratio: 0.3
  max_aspect_ratio: 3.0

# cat: 0 
# dog : 1 
  prob: 0.2  # Probability of applying blurring
  radius: 1.0  # Blur radius

# Noise
noise:
  enable: True  # Enable adding noise
  prob: 0.1  # Probability of adding noise
  amount: 0.01  # Noise amount

# Perspective Transform
perspective:
  enable: True  # Enable perspective transform
  prob: 0.05  # Probability of applying perspective transform
  distortion_scale: 0.1  # Amount of perspective distortion

# Random Erasing
random_erasing:
  enable: True  # Enable random erasing
  prob: 0.5  # Probability of applying random erasing
  min_area: 0.1  # Minimum area of the erased region
  max_area: 0.3  # Maximum area of the erased region
  min_aspect_ratio: 0.3  # Minimum aspect ratio of the erased region
  max_aspect_ratio: 3.0  # Maximum aspect ratio of the erased region
